### ISSUE TITLE
Keyboard pushes CoffeeInput out of frame

### ISSUE THREAD

**Issue by NateFuller** [johnmahlon/Coffee-Ratio#17]
Hey @johnmahlon - Trying to get my feet wet with SwiftUI and this is the perfect starter for me. Found this little visual bug with the keyboard on an iPhone 12 Pro Max simulator running iOS 14.5

![simulator_screenshot_EEDBACB5-502C-4369-8C4C-78891DDEDA52](https://user-images.githubusercontent.com/4147804/121027755-3937ee80-c775-11eb-8811-958bc453dce1.png)

I'm very familiar with building apps with Interface Builder but am brand new to SwiftUI. I'm going to tinker around and see if I can fix this issue. If you have any tips in the meantime, feel free to lmk here.

**Edit:** Realizing that the screenshot doesn't show the notch of the simulator. But the notch is blocking the view, so I'm guessing it's just a matter of telling the VStack to obey the safe area or something along those lines.

**Comment by Ravneet5911** [comment]
I would like to work on this issue, May I?

**Comment by johnmahlon** [comment]
@Ravneet6041 sure!

**Comment by Ravneet5911** [comment]
assign me plz

**Comment by Ravneet5911** [comment]
Hey @johnmahlon  
I have done with this issue and created a pull request for master. Kindly have a look on it and let me know if I miss something. Thanks
