### ISSUE TITLE
Suggestion: Timer UX

### ISSUE THREAD

**Issue by 68267a** [johnmahlon/Coffee-Ratio#4]
Overall this app is nearly perfect. However the Start/Clear/End buttons on the timer are a bit abstract, since the Start button does nothing when the timer is running and the end button does nothing when the timer is stopped. Suggestion:
1. Remove the End button. 
2. When the timer is running, Start should become Stop.
3. Rename End to Reset.
The goal is to have no useless buttons, and to follow naming conventions.

**Comment by johnmahlon** [comment]
Thank you for the suggestions! Its been a bit since I've worked on this, but I may have some time either this week or next week to check this out and update it.

**Comment by PointOfNilReturn** [comment]
Hi @johnmahlon, I made an attempt to change the UX/UI for the app and submitted a [PR](https://github.com/johnmahlon/Coffee-Ratio/pull/5). Hopefully these changes help make things more intuitive. Let me know if there is anything you would like me to change!

**Comment by johnmahlon** [comment]
@ChristopherAaronBrown I've merged your request. Thanks!!
